spring:
  application:
    name: hello-spring-cloud-zipkin
#解决The bean 'characterEncodingFilter', defined in class path resource [zipkin/autoconfigure/ui/ZipkinUiAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/HttpEncodingAutoConfiguration.class] and overriding is disabled.Action:
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:8084
server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#解决IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys.
management:
  metrics:
    web:
      server:
        auto-time-requests: false

